auth:
  postgresPassword: ${POSTGRES_PASSWORD}
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}

volumePermissions: true

Primary:
  livenessProbe:
    initialDelaySeconds: ${INITIAL_DELAY_SECONDS}
    periodSeconds: ${PERIOD_SECONDS}
    timeoutSeconds: ${TIMEOUT_SECONDS}
    successThreshold: ${SUCCESS_THRESHOLD}
    failureThreshold: ${FAILURE_THRESHOLD}

  readinessProbe:
    initialDelaySeconds: ${INITIAL_DELAY_SECONDS}
    periodSeconds: ${PERIOD_SECONDS}
    timeoutSeconds: ${TIMEOUT_SECONDS}
    successThreshold: ${SUCCESS_THRESHOLD}
    failureThreshold: ${FAILURE_THRESHOLD}
