apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager
subjects:
- kind: ServiceAccount
  name: sa_name
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: ca_name
  apiGroup: rbac.authorization.k8s.io
