apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests", "certificaterequests/status"]
  verbs: ["update"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "certificates/status"]
  verbs: ["update"]
- apiGroups: ["cert-manager.io"]
  resources: ["orders", "orders/status"]
  verbs: ["update"]
- apiGroups: ["acme.cert-manager.io"]
  resources: ["challenges", "challenges/status"]
  verbs: ["update"]
- apiGroups: ["acme.cert-manager.io"]
  resources: ["orders", "orders/status"]
  verbs: ["update"]

